services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - telemetry-network

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"  
      - "14250:14250"
    networks:
      - telemetry-network

  app:
    build: .
    depends_on:
      - otel-collector
      - jaeger
    networks:
      - telemetry-network

networks:
  telemetry-network: